version: '2'
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_STORAGE: azure
      REGISTRY_STORAGE_AZURE_ACCOUNTNAME: $AZURE_STORAGE_ACCOUNT
      REGISTRY_STORAGE_AZURE_CONTAINER: registry
      REGISTRY_STORAGE_AZURE_ACCOUNTKEY: $AZURE_STORAGE_ACCESS_KEY
  web:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "8000:80"
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000